# Generated by Django 5.1.3 on 2025-04-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Рейтинг ментора от 0.00 до 5.00.', max_digits=3, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество оставленных отзывов.', verbose_name='Количество отзывов'),
        ),
    ]
